# api errors
errors.api.analyse.actionDoesNotExists=Действие {0} не существует
errors.api.analyse.alreadyExecuted=Выполнение анализа с id={0} уже успешно завершено
errors.api.analyse.notFound=Анализ с id={0} не найден
errors.api.analyse.originalImage.notFound=Файл изображения для анализа id={0} не найден
errors.api.common.internalError=Произошла внутренняя ошибка
errors.api.patient.notFound=Пациент с id={0} не найден
errors.api.patient.policy.notFound=Пациент с номером полиса {0} не найден
errors.api.uploads.extensionNoAllowed=Расширение файла {0} не разрешено. Возможно расширения файлов: {1}
errors.api.uploads.fileIsEmpty=Файл пуст
errors.api.vessel.notFound=Сосуд с id={0} не найден

# validation errors

# other messages
analyse.status.extension.deletedByUser=Удален пользователем